
services:
  frontend:
    image: catarena/iu_hoa:latest  # Đổi thành image của front-end
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: catarena/web_hoa_client:latest  # Đổi tên image thành image API của bạn
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=https://zpsiohjshqnyovlckmpg.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwc2lvaGpzaHFueW92bGNrbXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjM2MzgsImV4cCI6MjA1ODc5OTYzOH0.n0RVmAtbybEILnwB1aE2mLD8KIFKkFU2lqDGcREBV34